/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e2e2e2",
        "on-tertiary": "#313030",
        "primary-fixed": "#d4ff00",
        "on-primary-fixed-variant": "#3e4c00",
        "error-container": "#93000a",
        "tertiary-container": "#e5e2e1",
        "surface-variant": "#333535",
        "surface-bright": "#37393a",
        "primary": "#ffffff",
        "primary-container": "#d4ff00",
        "surface-container-low": "#1a1c1c",
        "on-primary-fixed": "#171e00",
        "primary-fixed-dim": "#b0d500",
        "surface-container-high": "#282a2b",
        "tertiary": "#ffffff",
        "on-error": "#690005",
        "secondary": "#0033fe",
        "surface-container": "#1e2020",
        "surface-container-highest": "#333535",
        "tertiary-fixed-dim": "#c9c6c5",
        "outline": "#8c9378",
        "surface": "#121414",
        "on-surface": "#e2e2e2",
        "outline-variant": "#444932",
        "inverse-on-surface": "#2f3131",
        "secondary-fixed": "#dfe0ff",
        "on-secondary-fixed": "#ffffff",
        "secondary-container": "#0033fe",
        "surface-tint": "#d4ff00",
        "error": "#ffb4ab",
        "on-surface-variant": "#c5c9ac",
        "on-primary": "#2a3400",
        "on-primary-container": "#596c00",
        "on-secondary-container": "#ffffff",
        "tertiary-fixed": "#e5e2e1",
      },
      spacing: {
        "gutter": "24px",
      }
    },
  },
  plugins: [],
};
