/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e2e2e2",
        "on-tertiary": "#313030",
        "primary-fixed": "#ffe600",
        "on-primary-fixed-variant": "#665500",
        "error-container": "#93000a",
        "tertiary-container": "#e5e2e1",
        "surface-variant": "#333535",
        "surface-bright": "#37393a",
        "primary": "#ffffff",
        "primary-container": "#ffe600",
        "surface-container-low": "#1a1c1c",
        "on-primary-fixed": "#332A00",
        "primary-fixed-dim": "#e6cf00",
        "surface-container-high": "#282a2b",
        "tertiary": "#ffffff",
        "on-error": "#690005",
        "secondary": "#0033fe",
        "surface-container": "#1e2020",
        "surface-container-highest": "#333535",
        "tertiary-fixed-dim": "#c9c6c5",
        "outline": "#8c9378",
        "surface": "#121414",
        "on-surface": "#e2e2e2",
        "outline-variant": "#444932",
        "inverse-on-surface": "#2f3131",
        "secondary-fixed": "#dfe0ff",
        "on-secondary-fixed": "#ffffff",
        "secondary-container": "#0033fe",
        "surface-tint": "#ffe600",
        "error": "#ffb4ab",
        "on-surface-variant": "#c5c9ac",
        "on-primary": "#332A00",
        "on-primary-container": "#665500",
        "on-secondary-container": "#ffffff",
        "tertiary-fixed": "#e5e2e1",
      },
      spacing: {
        "xs": "8px",
        "sm": "16px",
        "base": "4px",
        "md": "32px",
        "lg": "64px",
        "xl": "128px",
        "gutter": "24px",
        "margin": "40px",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "label-bold": ["Space Grotesk"],
        "vertical-caption": ["Space Grotesk"],
        "body-base": ["Inter"],
        "headline-md": ["Inter"],
        "display-xl": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["64px", {"lineHeight": "110%", "letterSpacing": "-0.03em", "fontWeight": "800"}],
        "label-bold": ["14px", {"lineHeight": "100%", "letterSpacing": "0.1em", "fontWeight": "700"}],
        "vertical-caption": ["12px", {"lineHeight": "100%", "fontWeight": "500"}],
        "body-base": ["16px", {"lineHeight": "160%", "letterSpacing": "0em", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "120%", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "display-xl": ["120px", {"lineHeight": "100%", "letterSpacing": "-0.05em", "fontWeight": "900"}]
      }
    },
  },
  plugins: [],
};
